export const uiText = {
  "de": {
    "languageDe": "Deutsch",
    "languageFr": "Français",
    "mapCaption": "Der markierte Bereich zeigt euch ungefähr, wo ihr suchen müsst.",
    "zoomHint": "Zum Vergrößern antippen",
    "secretHintTitle": "Geheimer Hinweis",
    "accessTitle": "NUR FÜR ECHTE DETEKTIVE",
    "accessText": "Gebt euren Einsatz-Code ein, um die Mission freizuschalten.",
    "accessPlaceholder": "Einsatz-Code eingeben",
    "readyText": "Seid ihr bereit, Meister der Krümel aufzuhalten?",
    "checkingCode": "⏳ CODE WIRD GEPRÜFT...",
    "unlockButton": "🔓 MISSION FREISCHALTEN",
    "invalidCode": "Der Einsatz-Code ist leider nicht korrekt.",
    "emptyCode": "Bitte gebt einen Zugangscode ein.",
    "codeCheckUnavailable": "Die Code-Prüfung ist gerade nicht erreichbar. Bitte versucht es erneut.",
    "suddenlyQuiet": "Plötzlich wird es still…\n\nWas war das?",
    "lookButton": "🔎 Nachsehen",
    "oldBoxFound": "Da liegt etwas…\n\nEine alte Keksdose.\n\nSie ist verschlossen.",
    "inspectLockButton": "🔒 Schloss untersuchen",
    "beforeMission": "VOR DER MISSION",
    "startPlace": "📍 Kirche in Kappel-Grafenhausen (Kappel)",
    "startAddress": "Rathausstraße 52, 77966",
    "startHint": "Begebt euch zuerst zu diesem Ort.\nSobald ihr dort angekommen seid, tippt auf:",
    "atStart": "📍 Wir sind am Startpunkt",
    "mapsLink": "Startpunkt nicht gefunden? Route in Google Maps öffnen",
    "startMissionButton": "➜ STARTET JETZT EURE MISSION!",
    "showOrientation": "🧭 Orientierungshilfe anzeigen",
    "hideOrientation": "Orientierungshilfe ausblenden",
    "answerCheck": "Antwort prüfen",
    "answerWrong": "Hmm… das scheint noch nicht ganz zu stimmen.",
    "smallHint": "👀 Ein kleiner Hinweis",
    "moreHint": "👀 Noch ein Tipp anzeigen",
    "helpIntro": "Nur anklicken, wenn ihr wirklich nicht weiterkommt:",
    "planHelpButton": "👀 Wir brauchen Hilfe beim Fluchtplan",
    "solution": "Lösung anzeigen",
    "choiceWrongSuffix": "ist leider falsch. Schaut noch einmal genauer hin.",
    "fluchtplanWrong": "Schaut euch den geheimen Fluchtplan noch einmal ganz genau an.",
    "needPhoto": "Macht zuerst ein Teamfoto mit dem Spion.",
    "photoInfo": "📷 Das Foto bleibt nur auf eurem Gerät. Die App zeigt es nur als Vorschau.\nTipp: Nach dem Foto könnt ihr es zusätzlich speichern/herunterladen.",
    "photoTake": "📸 Teamfoto aufnehmen",
    "photoGallery": "🖼️ Foto aus Galerie auswählen",
    "photoSave": "💾 Foto auf Gerät speichern",
    "photoRetry": "Foto nochmal machen",
    "planAssemblyTitle": "🧩 Der zweite Teil des Fluchtplans",
    "planPart1Title": "Fluchtplan Teil 1",
    "planPart2Title": "Fluchtplan Teil 2",
    "planCompleteTitle": "Vollständiger Fluchtplan",
    "planAssemblySnapTitle": "KLICK!",
    "planAssemblySnapText": "Die beiden Teile passen perfekt zusammen...",
    "planAssemblyText": "Der Spion hält euch den zweiten Teil hin.\nWenn beide Stücke zusammenpassen, wisst ihr, wohin Meister der Krümel geflüchtet ist.",
    "planAssemblyButton": "🧩 Fluchtplan zusammensetzen",
    "planAssemblyWorking": "🧩 Wartet mal... jetzt ergibt alles Sinn!",
    "planAssemblyDoneText": "Wow!\n\nJetzt ergibt alles Sinn!\n\nIhr habt den kompletten Fluchtplan!",
    "lockOpened": "🔓 Schloss geöffnet",
    "lockOpen": "🔒 Schloss öffnen",
    "lockWrong": "Das ist leider nicht ganz richtig. Versucht es noch einmal.",
    "lockHint1Button": "👀 Hinweis 1 anzeigen",
    "lockHint2Button": "👀 Hinweis 2 anzeigen",
    "lockHint1Title": "Hinweis 1",
    "lockHint2Title": "Hinweis 2",
    "lockSolutionTitle": "Lösung",
    "lockHint1Text": "Erinnert euch:\nIhr braucht die erste Zahl, das geheime Tier und das geheime Zeichen.\nDenkt an die kleinen Helfer, das Tier vom Spielplatz und das Zeichen von Meister der Krümel.",
    "lockHint2Text": "Die erste Zahl ist die Anzahl der kleinen Helfer.\nIn der Mitte gehört das Tier, das alles beobachtet hat.\nRechts gehört das Zeichen, das Meister der Krümel bei der Eierkönigin hinterlassen hat.",
    "lockSolutionText": "Die richtige Kombination ist:\n3 – 🐘 Elefant – ☀️ Sonne",
    "formulaTitle": "🍪 DIE GEHEIME KEKSFORMEL",
    "formulaDownload": "📄 Keksformel herunterladen",
    "finaleQuietText": "Plötzlich wird es still…\n\nWas war das?",
    "finaleLookButton": "🔎 Nachsehen",
    "finaleBoxText": "Da liegt etwas…\n\nEine alte Keksdose.\n\nSie ist verschlossen.",
    "finaleInspectLockButton": "🔒 Schloss untersuchen",
    "reviewTitle": "Hat euch die Mission gefallen?",
    "reviewButton": "⭐ Bewertung bei Google abgeben",
    "missionCompletedTitle": "Mission abgeschlossen!",
    "teamPhotoTitle": "Euer Teamfoto",
    "returnTitle": "Zurück zum Startpunkt",
    "restartButton": "🔁 Diese Mission nochmal starten",
    "next": "Weiter",
    "footerImpressum": "Impressum",
    "footerDatenschutz": "Datenschutz",
    "menuTitle": "Menü",
    "faqTitle": "FAQ",
    "problemTitle": "Problem melden",
    "privacyHeading": "Datenschutzhinweis",
    "privacyText1": "Diese App speichert den Spielfortschritt lokal auf dem Gerät, damit die Mission bei einem versehentlichen Schließen fortgesetzt werden kann.",
    "privacyText2": "Das Teamfoto bleibt auf dem jeweiligen Gerät und wird nicht automatisch an uns übertragen.",
    "privacyText3": "Hier kannst du später deine vollständige Datenschutzerklärung einfügen.",
    "faqHeading": "Häufige Fragen",
    "faqItems": [
      {
        "question": "Was tun, wenn wir nicht weiterkommen?",
        "answer": "Nutzt zuerst die Hinweise in der jeweiligen Station."
      },
      {
        "question": "Was passiert mit dem Teamfoto?",
        "answer": "Das Foto bleibt auf eurem Gerät. Die App zeigt es nur als Vorschau."
      },
      {
        "question": "Wie lange dauert die Mission?",
        "answer": "Plant ungefähr 60 Minuten ein."
      }
    ],
    "problemIntro": "Wenn etwas nicht funktioniert, könnt ihr uns hier direkt eine kurze Meldung vorbereiten.",
    "problemStationLabel": "Station / Seite",
    "problemStationPlaceholder": "z. B. Station 5 / Schloss / Startseite",
    "problemDeviceLabel": "Gerät / Browser",
    "problemDevicePlaceholder": "z. B. iPhone Safari, Android Chrome",
    "problemDescriptionLabel": "Was ist passiert?",
    "problemDescriptionPlaceholder": "Beschreibt kurz, was nicht funktioniert hat.",
    "problemSendButton": "✉️ Problem per E-Mail melden",
    "problemSmallNote": "Hinweis: Es öffnet sich euer E-Mail-Programm. Die Nachricht wird erst versendet, wenn ihr sie dort abschickt.",
    "problemEmailSubject": "Problem bei der Schnitzeljagd-App"
  },
  "fr": {
    "languageDe": "Deutsch",
    "languageFr": "Français",
    "mapCaption": "La zone indiquée vous montre à peu près où chercher.",
    "zoomHint": "Touchez pour agrandir",
    "secretHintTitle": "Indice secret",
    "accessTitle": "RÉSERVÉ AUX VRAIS DÉTECTIVES",
    "accessText": "Entrez votre code de mission pour commencer l’aventure.",
    "accessPlaceholder": "Entrer le code de mission",
    "readyText": "Prêts à arrêter Maître Miette ?",
    "checkingCode": "⏳ VÉRIFICATION DU CODE...",
    "unlockButton": "🔓 COMMENCER L’AVENTURE",
    "invalidCode": "Ce code de mission n’est pas correct.",
    "emptyCode": "Veuillez entrer un code de mission.",
    "codeCheckUnavailable": "La vérification du code est momentanément indisponible. Veuillez réessayer.",
    "beforeMission": "AVANT LA MISSION",
    "startPlace": "📍 Église de Kappel-Grafenhausen (Kappel)",
    "startAddress": "Rathausstraße 52, 77966",
    "startHint": "Rendez-vous d’abord à cet endroit.\nUne fois arrivés, appuyez sur :",
    "atStart": "📍 Nous sommes au point de départ",
    "mapsLink": "Vous ne trouvez pas le départ ? Ouvrir l’itinéraire dans Google Maps",
    "startMissionButton": "➜ COMMENCEZ VOTRE MISSION !",
    "showOrientation": "🧭 Afficher l’aide d’orientation",
    "hideOrientation": "Masquer l’aide d’orientation",
    "answerCheck": "Vérifier la réponse",
    "answerWrong": "Hmm… ce n’est pas encore tout à fait ça.",
    "smallHint": "👀 Un petit indice",
    "moreHint": "👀 Encore un indice",
    "helpIntro": "À utiliser seulement si vous êtes vraiment bloqués :",
    "planHelpButton": "👀 Nous avons besoin d’aide avec le plan",
    "solution": "Afficher la solution",
    "choiceWrongSuffix": "n’est pas la bonne réponse. Regardez encore attentivement.",
    "fluchtplanWrong": "Regardez encore une fois le plan secret avec attention.",
    "needPhoto": "Faites d’abord une photo d’équipe avec l’espion.",
    "photoInfo": "📷 La photo reste uniquement sur votre appareil. L’app l’affiche seulement en aperçu.\nAstuce : après la photo, vous pouvez aussi l’enregistrer sur votre appareil.",
    "photoTake": "📸 Prendre la photo d’équipe",
    "photoGallery": "🖼️ Choisir une photo dans la galerie",
    "photoSave": "💾 Enregistrer la photo sur l’appareil",
    "photoRetry": "Refaire la photo",
    "planAssemblyTitle": "🧩 Le deuxième morceau du plan de fuite",
    "planPart1Title": "Plan de fuite – partie 1",
    "planPart2Title": "Plan de fuite – partie 2",
    "planCompleteTitle": "Plan de fuite complet",
    "planAssemblySnapTitle": "CLIC !",
    "planAssemblySnapText": "Les deux morceaux s’assemblent parfaitement...",
    "planAssemblyText": "L’espion vous tend le deuxième morceau.\nQuand les deux morceaux s’assemblent, vous saurez où Maître Miette s’est enfui.",
    "planAssemblyButton": "🧩 Assembler le plan de fuite",
    "planAssemblyWorking": "🧩 Attendez… tout devient clair !",
    "planAssemblyDoneText": "Waouh !\n\nMaintenant tout s’explique !\n\nVous avez le plan de fuite complet !",
    "lockOpened": "🔓 Cadenas ouvert",
    "lockOpen": "🔒 Ouvrir le cadenas",
    "lockWrong": "Ce n’est pas encore la bonne combinaison. Essayez encore.",
    "lockHint1Button": "👀 Afficher l’indice 1",
    "lockHint2Button": "👀 Afficher l’indice 2",
    "lockHint1Title": "Indice 1",
    "lockHint2Title": "Indice 2",
    "lockSolutionTitle": "Solution",
    "lockHint1Text": "Souvenez-vous :\nIl vous faut le premier nombre, l’animal secret et le signe secret.\nPensez aux petits aides, à l’animal du terrain de jeux et au signe de Maître Miette.",
    "lockHint2Text": "Le premier élément est le nombre des petits aides.\nAu milieu vient l’animal qui a tout observé.\nÀ droite vient le signe laissé par Maître Miette chez la reine des œufs.",
    "lockSolutionText": "La bonne combinaison est :\n3 – 🐘 Éléphant – ☀️ Soleil",
    "formulaTitle": "🍪 LA RECETTE SECRÈTE",
    "formulaDownload": "📄 Télécharger la recette",
    "finaleQuietText": "Soudain, tout devient silencieux…\n\nQu’est-ce que c’était ?",
    "finaleLookButton": "🔎 Aller voir",
    "finaleBoxText": "Il y a quelque chose là-bas…\n\nUne vieille boîte à biscuits.\n\nElle est fermée.",
    "finaleInspectLockButton": "🔒 Examiner le cadenas",
    "reviewTitle": "La mission vous a plu ?",
    "reviewButton": "⭐ Laisser un avis Google",
    "missionCompletedTitle": "Mission accomplie !",
    "teamPhotoTitle": "Votre photo d’équipe",
    "returnTitle": "Retour au point de départ",
    "restartButton": "🔁 Rejouer cette mission",
    "next": "Continuer",
    "footerImpressum": "Mentions légales",
    "footerDatenschutz": "Confidentialité",
    "menuTitle": "Menu",
    "faqTitle": "FAQ",
    "problemTitle": "Signaler un problème",
    "privacyHeading": "Note de confidentialité",
    "privacyText1": "Cette app enregistre la progression du jeu localement sur l’appareil afin que la mission puisse être reprise si elle est fermée par accident.",
    "privacyText2": "La photo d’équipe reste sur l’appareil utilisé et n’est pas transmise automatiquement.",
    "privacyText3": "Vous pourrez ajouter ici votre déclaration de confidentialité complète plus tard.",
    "faqHeading": "Questions fréquentes",
    "faqItems": [
      {
        "question": "Que faire si nous sommes bloqués ?",
        "answer": "Utilisez d’abord les indices de la station concernée."
      },
      {
        "question": "Que devient la photo d’équipe ?",
        "answer": "La photo reste sur votre appareil. L’app l’affiche uniquement en aperçu."
      },
      {
        "question": "Combien de temps dure la mission ?",
        "answer": "Prévoyez environ 60 minutes."
      }
    ],
    "problemIntro": "Si quelque chose ne fonctionne pas, vous pouvez préparer ici un court message à nous envoyer.",
    "problemStationLabel": "Étape / page",
    "problemStationPlaceholder": "p. ex. Étape 5 / cadenas / page de départ",
    "problemDeviceLabel": "Appareil / navigateur",
    "problemDevicePlaceholder": "p. ex. iPhone Safari, Android Chrome",
    "problemDescriptionLabel": "Que s’est-il passé ?",
    "problemDescriptionPlaceholder": "Décrivez brièvement ce qui n’a pas fonctionné.",
    "problemSendButton": "✉️ Signaler le problème par e-mail",
    "problemSmallNote": "Remarque : votre programme de messagerie s’ouvre. Le message ne sera envoyé que lorsque vous l’enverrez depuis celui-ci.",
    "problemEmailSubject": "Problème avec l’app de chasse au trésor"
  },
  "en": {
    "languageDe": "Deutsch",
    "languageFr": "Français",
    "languageEn": "English",
    "mapCaption": "The marked area shows roughly where you need to search.",
    "zoomHint": "Tap to enlarge",
    "secretHintTitle": "Secret hint",
    "accessTitle": "FOR REAL DETECTIVES ONLY",
    "accessText": "Enter your mission code to unlock the adventure.",
    "accessPlaceholder": "Enter mission code",
    "readyText": "Are you ready to stop Master Crumble?",
    "checkingCode": "⏳ CHECKING CODE...",
    "unlockButton": "🔓 UNLOCK MISSION",
    "invalidCode": "This mission code is not correct.",
    "emptyCode": "Please enter a mission code.",
    "codeCheckUnavailable": "Code checking is currently unavailable. Please try again.",
    "beforeMission": "BEFORE THE MISSION",
    "startPlace": "📍 Church in Kappel-Grafenhausen (Kappel)",
    "startAddress": "Rathausstraße 52, 77966",
    "startHint": "First go to this place.\nOnce you have arrived, tap:",
    "atStart": "📍 We are at the starting point",
    "mapsLink": "Can’t find the start? Open the route in Google Maps",
    "startMissionButton": "➜ START YOUR MISSION NOW!",
    "showOrientation": "🧭 Show orientation help",
    "hideOrientation": "Hide orientation help",
    "answerCheck": "Check answer",
    "answerWrong": "Hmm… that does not seem quite right yet.",
    "smallHint": "👀 A small hint",
    "moreHint": "👀 Show another hint",
    "helpIntro": "Only tap this if you are really stuck:",
    "planHelpButton": "👀 We need help with the escape plan",
    "solution": "Show solution",
    "choiceWrongSuffix": "is not the correct answer. Look more carefully.",
    "fluchtplanWrong": "Look at the secret escape plan very carefully again.",
    "needPhoto": "Take a team photo with the spy first.",
    "photoInfo": "📷 The photo stays only on your device. The app only shows it as a preview.\nTip: After taking the photo, you can also save/download it.",
    "photoTake": "📸 Take team photo",
    "photoGallery": "🖼️ Choose photo from gallery",
    "photoSave": "💾 Save photo to device",
    "photoRetry": "Take another photo",
    "planAssemblyTitle": "🧩 The second part of the escape plan",
    "planPart1Title": "Escape plan part 1",
    "planPart2Title": "Escape plan part 2",
    "planCompleteTitle": "Complete escape plan",
    "planAssemblySnapTitle": "CLICK!",
    "planAssemblySnapText": "The two pieces fit together perfectly...",
    "planAssemblyText": "The spy hands you the second part.\nWhen both pieces fit together, you will know where Master Crumble escaped to.",
    "planAssemblyButton": "🧩 Put the escape plan together",
    "planAssemblyWorking": "🧩 Wait... now everything makes sense!",
    "planAssemblyDoneText": "Wow!\n\nNow everything makes sense!\n\nYou have the complete escape plan!",
    "lockOpened": "🔓 Lock opened",
    "lockOpen": "🔒 Open lock",
    "lockWrong": "That is not quite right. Try again.",
    "lockHint1Button": "👀 Show hint 1",
    "lockHint2Button": "👀 Show hint 2",
    "lockHint1Title": "Hint 1",
    "lockHint2Title": "Hint 2",
    "lockSolutionTitle": "Solution",
    "lockHint1Text": "Remember:\nYou need the first number, the secret animal and the secret sign.\nThink of the little helpers, the animal from the playground and Master Crumble’s sign.",
    "lockHint2Text": "The first element is the number of little helpers.\nIn the middle goes the animal that saw everything.\nOn the right goes the sign Master Crumble left at the egg queen’s house.",
    "lockSolutionText": "The correct combination is:\n3 – 🐘 Elephant – ☀️ Sun",
    "formulaTitle": "🍪 THE SECRET COOKIE FORMULA",
    "formulaDownload": "📄 Download cookie formula",
    "finaleQuietText": "Suddenly everything goes quiet…\n\nWhat was that?",
    "finaleLookButton": "🔎 Go and look",
    "finaleBoxText": "There is something lying there…\n\nAn old cookie tin.\n\nIt is locked.",
    "finaleInspectLockButton": "🔒 Inspect the lock",
    "reviewTitle": "Did you enjoy the mission?",
    "reviewButton": "⭐ Leave a Google review",
    "missionCompletedTitle": "Mission completed!",
    "teamPhotoTitle": "Your team photo",
    "returnTitle": "Back to the starting point",
    "restartButton": "🔁 Restart this mission",
    "next": "Continue",
    "footerImpressum": "Legal notice",
    "footerDatenschutz": "Privacy",
    "menuTitle": "Menu",
    "faqTitle": "FAQ",
    "problemTitle": "Report a problem",
    "privacyHeading": "Privacy note",
    "privacyText1": "This app stores game progress locally on the device so the mission can be continued if it is closed by accident.",
    "privacyText2": "The team photo stays on the device and is not automatically sent to us.",
    "privacyText3": "You can add your full privacy policy here later.",
    "faqHeading": "Frequently asked questions",
    "faqItems": [
      {
        "question": "What should we do if we get stuck?",
        "answer": "Use the hints at the current station first."
      },
      {
        "question": "What happens to the team photo?",
        "answer": "The photo stays on your device. The app only shows it as a preview."
      },
      {
        "question": "How long does the mission take?",
        "answer": "Plan for about 60 minutes."
      }
    ],
    "problemIntro": "If something does not work, you can prepare a short message to us here.",
    "problemStationLabel": "Station / page",
    "problemStationPlaceholder": "e.g. Station 5 / lock / start page",
    "problemDeviceLabel": "Device / browser",
    "problemDevicePlaceholder": "e.g. iPhone Safari, Android Chrome",
    "problemDescriptionLabel": "What happened?",
    "problemDescriptionPlaceholder": "Briefly describe what did not work.",
    "problemSendButton": "✉️ Report problem by email",
    "problemSmallNote": "Note: Your email program will open. The message is only sent when you send it there.",
    "problemEmailSubject": "Problem with the treasure hunt app"
  }
};
